#!/bin/sh


#chkconfig: 2345 80 90

#description: mongodb
start() {
  /home/mongodb_simple/bin/mongod -f /home/mongodb_simple/conf/mongo.conf
}

stop() {
  /home/mongodb_simple/bin/mongod -f /home/mongodb_simple/conf/mongo.conf --shutdown
}

case "$1" in
  start)
 start
 ;;
  stop)
 stop
 ;;
  restart)
 stop
 start
 ;;
  *)
 echo $"Usage: $0 {start|stop|restart}"
 exit 1
esac

